CREATE DATABASE TIENDABD;

CREATE TABLE PERSONA (
    IDPERSONA INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDO NVARCHAR(50) NOT NULL,
    TELEFONO NVARCHAR(50) NOT NULL,
    CI NVARCHAR(10) NOT NULL,
    CORREO NVARCHAR(20) NOT NULL,
    ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDPERSONA)
);
CREATE TABLE TIPOPRODUCTO(
	IDTIPOPRODUCTO INT IDENTITY (1,1) NOT NULL,
	NOMBRE VARCHAR(50),
	ESTADO VARCHAR(20),
	PRIMARY KEY (IDTIPOPRODUCTO)
);
CREATE TABLE MARCA(
	IDMARCA INT IDENTITY (1,1) NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDMARCA)
);
CREATE TABLE ROL(
	IDROL INT IDENTITY (1,1) NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDROL)
);
CREATE TABLE PROVEEDOR(
	IDPROVEEDOR INT IDENTITY (1,1) NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	TELEFONO NVARCHAR(50) NOT NULL,
	DIRECCION NVARCHAR(50) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDPROVEEDOR)
);
CREATE TABLE PRODUCTO(
	IDPRODUCTO INT IDENTITY (1,1) NOT NULL,
	IDTIPOPRODUCTO INT NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	CODIGOBARRA NVARCHAR(20) NOT NULL,
	IDMARCA INT NOT NULL,
	UNIDAD NVARCHAR(20) NOT NULL,
	DESCRIPCION NVARCHAR(20) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDPRODUCTO),
	FOREIGN KEY (IDTIPOPRODUCTO) REFERENCES TIPOPRODUCTO (IDTIPOPRODUCTO),
	FOREIGN KEY (IDMARCA) REFERENCES MARCA (IDMARCA)
);
CREATE TABLE CLIENTE(
	IDCLIENTE INT IDENTITY (1,1) NOT NULL,
	IDPERSONA INT NOT NULL,
	TIPOCLIENTE NVARCHAR(20) NOT NULL,
	CODIGOCLIETE NVARCHAR(20) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDCLIENTE),
	FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA)
);
CREATE TABLE USUARIO(
	IDUSUARIO INT IDENTITY (1,1) NOT NULL,
	IDPERSONA INT NOT NULL,
	NOMBREUSER NVARCHAR(50) NOT NULL,
	CONTRASEÑA NVARCHAR(50) NOT NULL,
	FECHAREG DATETIME NOT NULL,
	PRIMARY KEY (IDUSUARIO),
	FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA),
);

CREATE TABLE USUARIOROL(
	IDUSUARIOROL INT IDENTITY (1,1) NOT NULL,
	IDUSUARIO INT NOT NULL,
	IDROL INT NOT NULL,
	FECHAASIGNA DATETIME NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDUSUARIOROL),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO),
	FOREIGN KEY (IDROL) REFERENCES ROL (IDROL)
);
CREATE TABLE INGRESO(
	IDINGRESO INT IDENTITY (1,1) NOT NULL,
	IDPROVEEDOR INT NOT NULL,
	FECHAINGRESO DATETIME NOT NULL,
	TOTAL NVARCHAR(20) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDINGRESO),
	FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (IDPROVEEDOR),
);
CREATE TABLE DETALLEING(
	IDDETALLEVEING INT IDENTITY (1,1) NOT NULL,
	IDPRODUCTO INT NOT NULL,
	IDINGRESO INT NOT NULL,
	FECHAVENC DATETIME NOT NULL,
	CANTIDAD NVARCHAR(20) NOT NULL,
	PRECIOCOSTO NVARCHAR(20) NOT NULL,
	PRECIOVENTA NVARCHAR(20) NOT NULL,
	SUBTOTAL NVARCHAR(20) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDDETALLEVEING),
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO),
	FOREIGN KEY (IDINGRESO) REFERENCES INGRESO (IDINGRESO)
);
CREATE TABLE VENTA(
	IDVENTA INT IDENTITY (1,1) NOT NULL,
	IDCLIENTE INT NOT NULL,
	IDVENDEDOR INT NOT NULL,
	FECHA DATETIME NOT NULL,
	TOTAL NVARCHAR(20) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDVENTA),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
	FOREIGN KEY (IDVENDEDOR) REFERENCES USUARIO (IDUSUARIO)
);
CREATE TABLE DETALLEVENTA(
	IDDETALLEVENTA INT IDENTITY (1,1) NOT NULL,
	IDVENTA INT NOT NULL,
	IDPRODUCTO INT NOT NULL,
	CANTIDAD NVARCHAR(20) NOT NULL,
	PRECIOVENTA NVARCHAR(20) NOT NULL,
	SUBTOTAL NVARCHAR(20) NOT NULL,
	ESTADO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDDETALLEVENTA),
	FOREIGN KEY (IDVENTA) REFERENCES VENTA (IDVENTA),
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO)
);

CREATE TABLE PROVEE(
	IDPROVEE INT IDENTITY (1,1) NOT NULL,
	IDPRODUCTO INT NOT NULL,
	IDPROVEEDOR INT NOT NULL,
	FECHA DATETIME NOT NULL,
	PRECIO NVARCHAR(20) NOT NULL,
	PRIMARY KEY (IDPROVEE),
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO),
	FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (IDPROVEEDOR)
);



